### ISSUE TITLE
Dummy Issue 1: treat as CF Conventions standard name proposal

### ISSUE THREAD

**Issue by sadielbartholomew** [sadielbartholomew/crash_test_dummy#1]
(For testing cf-convention/discuss#175, with equivalent files previously added under `.github` with timings bumper down to 1 day only to make it quicker to check the behaviour is as desired.)

**Comment by sadielbartholomew** [comment]
I was hoping a comment would automatically be added here via `hramos/label-actions@v1` since I added the `standard name` label and triggered by the Actions workflow https://github.com/sadielbartholomew/crash_test_dummy/blob/main/.github/workflows/process-labels.yml, but not seeing anything yet...

Anyway, to test the staleness component I need this to be left uncommented on for a few days, so I'll shut up and see what happens(!)...

**Comment by feggleton** [comment]
this is really odd as i just tested on my fork - added a plain issue and added label later https://github.com/feggleton/discuss/issues/11 and comment was triggered

when you look at my action is has no errors but does have the node.js warning whereas yours has node.js errors which aren't be handled well. I can see there is a depreciation which links to hramos/label-actions@v1 which is an issue with the owner of the action. There is another action for the same thing here https://github.com/dessant/label-actions which we could switch to.

Also your github action has closed the issue, mine does not do that.

**Comment by sadielbartholomew** [comment]
Hi @feggleton, firstly sorry that you got tagged in this - I am using this for testing and should have removed the tag on your name. And then the plan was to link to it in a PR review with explanation of what I'd done and observed. But you've clearly worked out what the context is! :slightly_smiling_face: 

Thanks for reporting what you expected in terms of behaviour. I was about to go to the main PR to ask, since two of the automatic events which happened were as I expected, namely the:

* (A) triggering of the staleness notification comment (https://github.com/sadielbartholomew/crash_test_dummy/issues/1#issuecomment-1443256943) by the lack of activity on the Issue; and
* (B) the closure of the Issue, after a further period of time (which I lowered to 1 day);

but one thing which I thought would that didn't, namely:

* (C) the triggering of the introductory comment ("Thank you for your proposal. These terms will ...") by the 'standard name' tag I added early on.

From your comment:

> this is really odd as i just tested on my fork - added a plain issue and added label later https://github.com/feggleton/discuss/issues/11 and comment was triggered

it seems that it was indeed intended that (C) should happen. I'm also quite unsure as to why (C) didn't happen on my issue here but did on yours in https://github.com/feggleton/discuss/issues/11. I wonder if it might be to do with the fact that I hadn't created a 'standard name' label until the Issue was opened. In which case, I can test that by opening another Issue, which I will do in a moment. But I am satisfied it is working if it works on your fork!, so review-wise that's all good (ideally, of course, we can work out why it isn't working here as well...)

> when you look at my action is has no errors but does have the node.js warning whereas yours has node.js errors which aren't be handled well

Good thinking, I didn't think to check the Actions job log. I'll see if there's anything that might be useful, but it is indeed weird if there's different error/warning outputs on my Issue here on this repo and your fork of `discuss` (the fork of yours is a better gauge though so that's the most important I think!).

> Also your github action has closed the issue, mine does not do that.

When I added the equivalent workflow files to this repo, I lowered the `days-before-stale` flag down to `1` day so it wouldn't take increments of a month to review (which would be very slow going :smiley:), and re-enabled the closure via changing  `days-before-close` to `1` also (for (B) to happen, I'm not sure if you want that in the final workflow or not?): see my commit https://github.com/sadielbartholomew/crash_test_dummy/commit/fd5175feb411fa626364e6411f2230df4064796f. So for your fork, the steps triggered above should almost certainly happen, just not for 30 days (30 + 2 for the closure based on the gap between the two events triggering here)!

***

So overall everything is looking good, but I'll try to work out why the introduction comment (C) wasn't triggered here, by opening another issue.

**Comment by feggleton** [comment]
No worries at all! I'm still very confused as to why the initial message hasn't shown on this issue or the other test. I'll do more tests on my repo but then it might be a case or rolling it out and trailing it. The only thing I could think of was that the label might be different or spelt wrong but it doesn't seem to be. 

Oh I see you've edited slightly - that's of course fine. I made it so that the issues didn't close automatically as I didn't think this would work well for standard name requests and the timescales of activity, issues would probably get closed and forgotten about.

Thanks for testing!
